### PR TITLE
Revert "Merge Gripper subsystem into Main"

### PR DESCRIPTION
**Pull request by kennlw**
Reverts Robotiators-888/2023Season#13

Messed up the merge, need to be reverted.

### CODE REVIEW

**Review by organelleV — APPROVED** [review]
looks like it will revert to the commit before the merge.

**Review by hanoiBat — APPROVED** [review]
Looks good to me!

**Comment by Spenceroni-Pepperoni** [comment]
Why is this needed?

**Comment by Spenceroni-Pepperoni** [comment]
Fixed with manual pushes to main by me

**Pull request closed without merging**
